"""esquema inicial

NOTA: los predicados de los índices parciales se corrigieron a mano. El
autogenerate se ejecutó contra SQLite (no había Postgres disponible) y dejó
`IS 1`, que Postgres rechaza. La versión correcta usa `IS true` para
postgresql_where y `IS 1` para sqlite_where.

Al regenerar migraciones contra Postgres, esta corrección deja de ser
necesaria — pero conviene revisar cualquier índice parcial nuevo.


Revision ID: 354bc5f3ef32
Revises: 
Create Date: 2026-08-21 21:39:11.017359
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '354bc5f3ef32'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_library',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('bible', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('avg_realism_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('campaign_goal', sa.String(length=60), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('target_duration_sec', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=20), nullable=False),
    sa.Column('stage_status', sa.String(length=30), nullable=False),
    sa.Column('auto_mode', sa.Boolean(), nullable=False),
    sa.Column('retry_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_projects_stage', 'projects', ['current_stage', 'stage_status'], unique=False)
    op.create_table('prompt_library',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('agent_number BETWEEN 1 AND 12', name='ck_prompt_agent_number'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('avatar_references',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('avatar_id', sa.String(length=32), nullable=False),
    sa.Column('angle', sa.String(length=20), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar_id', 'angle', name='uq_avatar_angle')
    )
    op.create_table('campaign_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('hook_rate', sa.Float(), nullable=True),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('spend_usd', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'measured_at', name='uq_metric_day')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('start_sec', sa.Float(), nullable=True),
    sa.Column('end_sec', sa.Float(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('avatar_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_audit_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar_library.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_clip_code')
    )
    op.create_table('creative_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_value', sa.String(length=120), nullable=True),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_project_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('alta','media','baja')", name='ck_memory_confidence'),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_scope', 'creative_memory', ['scope', 'scope_value', 'is_active'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('prompt_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_audit_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_version')
    )
    op.create_index('idx_prompt_one_active', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where=sa.text('is_active IS true'), sqlite_where=sa.text('is_active IS 1'))
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('input_ref', sa.String(length=32), nullable=True),
    sa.Column('clip_id', sa.String(length=32), nullable=True),
    sa.Column('clip_key', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_ref'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'type', 'version', 'clip_key', name='uq_artifact_version')
    )
    op.create_index('idx_artifacts_lookup', 'artifacts', ['project_id', 'type', 'status', 'version'], unique=False)
    op.create_table('clip_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clip_id', sa.String(length=32), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('realism_score', sa.Integer(), nullable=False),
    sa.Column('ad_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('issue_category', sa.String(length=30), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('route_to_agent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision = 'approved' OR route_to_agent IS NOT NULL", name='ck_audit_route_required'),
    sa.CheckConstraint('route_to_agent IS NULL OR route_to_agent BETWEEN 1 AND 12', name='ck_audit_route_range'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('clip_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_job_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('polls', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result_url', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idempotency')
    )
    op.create_index('idx_jobs_inflight', 'jobs', ['status', 'provider_job_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('clip_id', sa.String(length=32), nullable=True),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('output_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('prompt_version_id', sa.String(length=32), nullable=True),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('agent_number BETWEEN 1 AND 12', name='ck_agent_number'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_agent', 'agent_runs', ['agent_number', 'status'], unique=False)
    op.create_index('idx_runs_project', 'agent_runs', ['project_id', 'started_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('clip_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_clip', 'assets', ['clip_id', 'kind', 'version'], unique=False)
    op.create_index('idx_assets_one_selected', 'assets', ['clip_id', 'kind'], unique=True, postgresql_where=sa.text('is_selected IS true'), sqlite_where=sa.text('is_selected IS 1'))
    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.String(length=16), nullable=True),
    sa.Column('decided_by', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('approved','rejected','edited')", name='ck_approval_decision'),
    sa.CheckConstraint('artifact_id IS NOT NULL OR asset_id IS NOT NULL', name='ck_approval_target'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_index('idx_assets_one_selected', table_name='assets', postgresql_where=sa.text('is_selected IS true'), sqlite_where=sa.text('is_selected IS 1'))
    op.drop_index('idx_assets_clip', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_runs_project', table_name='agent_runs')
    op.drop_index('idx_runs_agent', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('idx_jobs_inflight', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('clip_audits')
    op.drop_index('idx_artifacts_lookup', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_prompt_one_active', table_name='prompt_versions', postgresql_where=sa.text('is_active IS true'), sqlite_where=sa.text('is_active IS 1'))
    op.drop_table('prompt_versions')
    op.drop_index('idx_memory_scope', table_name='creative_memory')
    op.drop_table('creative_memory')
    op.drop_table('clips')
    op.drop_table('campaign_metrics')
    op.drop_table('avatar_references')
    op.drop_table('prompt_library')
    op.drop_index('idx_projects_stage', table_name='projects')
    op.drop_table('projects')
    op.drop_table('avatar_library')
    # ### end Alembic commands ###
